### ISSUE TITLE
doesn't work for me too

### ISSUE THREAD

**Issue by nikivdev** [mklabs/yarn-completions#3]
I downloaded it with 'yarn global add' but it doesn't seem to work.

Writing yarn and pressing tab I get this : 

![](https://i.imgur.com/0CpnGUA.png)

**Comment by mklabs** [comment]
Hi,

Have you tested it with npm also ? What is your shell ? is your SHELL config file updated with tabtab line to load the completion function ?

I quickly tested it and yarn global add seems to trigger the postinstall script but I might be wrong.

**Comment by nikivdev** [comment]
Hey,

NPM autocomplete works. My shell is zsh. I don't think my shell got updated in any way. Perhaps this is the issue.

**Comment by mklabs** [comment]
I think this is the issue.

I meant, did you try installing yarn-completions with npm instead of yarn ? I suspect that yarn global add doesn't trigger the install script.

```
yarn global remove yarn-completions
npm install yarn-completions -g
```

Just to see if your shell gets updated by tabtab. At the end of your bashrc, you should have a line added by tabtab to load the completion function specific to your shell.

**Comment by denizdogan** [comment]
I just installed this package using Yarn using zsh with no problem whatsoever. Make sure to source your ~/.zshrc like:

    $ source ~/.zshrc

...or just start a new zsh.
